/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current positions and account equity
         * @description All held positions plus account equity (cash + mark-to-market positions value).
         *     `current_price`/`unrealized_pnl_pct` on each position are enriched from the market
         *     data cache and are null only if a price fetch for that ticker has failed. A position
         *     whose price couldn't be fetched contributes nothing to `equity.positions_value`
         *     (it can't be marked to market) rather than falling back to cost basis — see this
         *     task's `decisions` entry. The fetch-and-degrade-gracefully loop itself lives in
         *     `app.portfolio.pricing` (shared with GET /api/portfolio/risk) — see the
         *     api-portfolio-risk task's `decisions` entry.
         */
        get: operations["get_portfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add or update a position
         * @description Creates a position from manual entry / CSV-import data. If a position for this ticker
         *     already exists it is merged rather than duplicated: quantities are summed and
         *     avg_cost_basis becomes the quantity-weighted average of the existing and incoming cost
         *     bases (mirrors how a brokerage averages up/down a position instead of tracking separate
         *     lots) — see the api-portfolio-add-position task's `decisions` for the full rationale and
         *     the rejected reject-with-409 alternative. entry_date keeps the earlier of the two dates.
         *     `current_price`/`unrealized_pnl_pct` are always null here: price enrichment happens on
         *     read (GET /api/portfolio), not on write, and isn't available until the data-cache task
         *     lands.
         */
        post: operations["add_position"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a position
         * @description Removes a position entirely. There is no partial-quantity reduction endpoint —
         *     reducing a position means deleting and re-adding it with the new quantity.
         */
        delete: operations["delete_position"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the 2%/6% rule evaluation and per-position exit flags
         * @description Per-position protective stop, 2%-rule risk, and exit flags, plus the portfolio-wide
         *     6%-rule total (docs/Analyse.md §7). `exit_flags` can be non-empty even when the
         *     corresponding stock's fresh technical signal is HOLD — risk-driven exits are
         *     independent of entry-signal logic by design.
         *
         *     A position is silently excluded from `positions` (and so from `total_open_risk_pct`,
         *     which only sums positions with a known stop — see `app.portfolio.risk
         *     .total_open_risk_pct`) whenever its risk can't be computed at all: its current price
         *     couldn't be fetched (same degrade-gracefully rule as GET /api/portfolio — see this
         *     task's `decisions` entry), its daily history has fewer than 2 rows once any malformed
         *     bar is dropped (the minimum `evaluate_exit_flags` needs to test today's close against
         *     yesterday's stop), its weekly history couldn't be fetched, or
         *     `protective_stop`/`evaluate_exit_flags` raised for a malformed frame. `RiskPosition`'s
         *     fields are all non-nullable, so a position that can't be fully evaluated has no partial
         *     representation in this schema — see this task's `decisions` entry.
         *
         *     `e.daily_ohlcv` is passed through `app.signals.engine.drop_malformed_daily_bars` before
         *     `protective_stop`/`evaluate_exit_flags` ever see it — mirroring GET
         *     /api/stocks/{ticker}/analysis's identical filtering — so a malformed bar anywhere in a
         *     position's history can't silently suppress an exit flag via a NaN comparison quietly
         *     evaluating False. Called here with `require_full_ohlc_on_latest_bar=False`, unlike GET
         *     /api/stocks/{ticker}/analysis's default-`True` call: the *latest* bar is dropped only if
         *     its own `close` is NaN, matching `app.portfolio.pricing._latest_close`'s own close-only
         *     validity rule for that exact bar (which is what `position.current_price` was derived
         *     from), rather than also requiring open/high/low there — a shape `_latest_close` doesn't
         *     guard against, and one this pipeline's own downstream reads (`evaluate_exit_flags` and
         *     everything it calls) never touch for the latest bar anyway. Using the stricter default here
         *     would silently drop a real latest bar whose close is valid but whose open/high/low haven't
         *     settled yet, desyncing `position.current_price` from `daily_ohlcv`'s last row and making
         *     `evaluate_exit_flags` test yesterday's close against today's stop instead of today's — see
         *     the api-stocks-analysis-nullable-indicators-followups task's `decisions` entry for the full
         *     reasoning and the regression this reconciles.
         */
        get: operations["get_portfolio_risk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Triple Screen signal, confidence, and indicator breakdown
         * @description Runs the full Triple Screen evaluation (tide, wave, trigger, Impulse gate) and the
         *     weighted confidence score for `ticker` (docs/Analyse.md §2-6). `confidence_breakdown`
         *     exposes the per-component scores so the signal is auditable, not just a bare number.
         *
         *     `ticker` is normalized to uppercase (mirrors `POST /api/portfolio/positions`'s handling
         *     of the same field) before being passed to the data provider and echoed back in the
         *     response. Daily and weekly OHLCV are fetched via the SQLite-backed cache
         *     (`app.data.cache.CachedDataProvider`, docs/architecture/Backend.md §7); the weekly fetch
         *     is what actually enforces the <26-week-history -> 422 rule
         *     (`app.data.yfinance_provider.YFinanceProvider._MIN_WEEKLY_BARS`) -- this handler adds no
         *     separate minimum-history check of its own, matching `app.signals.engine.analyse`'s own
         *     documented degrade-gracefully-to-HOLD behavior for a short/empty daily series (see this
         *     task's `decisions` entry).
         *
         *     `daily_ohlcv` has any malformed bar (NaN open/high/low/close -- a real observed
         *     unsettled-latest-bar condition) dropped via `app.signals.engine.drop_malformed_daily_bars`
         *     before `as_of` is derived from it, so `as_of` reflects the same freshest *real* bar that
         *     actually drove `analyse()` -- not a malformed bar `analyse()` itself excludes internally
         *     anyway (see that function's own docstring and this task's `decisions` entry).
         */
        get: operations["get_stock_analysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OHLCV price history
         * @description Raw OHLCV bars for charting, served from the SQLite cache (docs/architecture/Backend.md §7)
         *     and backfilled from yfinance/Stooq on a cache miss. Weekly bars are yfinance's native
         *     weekly interval, not a manual resample of daily bars, per docs/Analyse.md §9.
         *
         *     `ticker` is normalized to uppercase, matching `GET /api/stocks/{ticker}/analysis` and
         *     `POST /api/portfolio/positions`. Only the interval actually requested is fetched (unlike
         *     `/analysis`, which always needs both) -- so a `weekly`-interval request is the only way
         *     this endpoint can itself raise the same <26-week `InsufficientHistoryError` -> 422 that
         *     `/analysis`'s weekly fetch enforces (`app.data.yfinance_provider.YFinanceProvider._MIN_WEEKLY_BARS`);
         *     see this task's `decisions` entry for why that's surfaced here too rather than only for
         *     computed indicators.
         */
        get: operations["get_stock_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical indicator values and the resulting signal for each daily bar
         * @description Re-runs the Triple Screen signal engine (`app.signals.engine.analyse`, via
         *     `app.signals.engine.analyse_history`) once per daily bar in the requested range, each time
         *     using only that bar's own history (no look-ahead) -- so the frontend can plot indicator
         *     lines and BUY/SELL/HOLD markers over time, instead of only the latest-bar snapshot
         *     `GET /api/stocks/{ticker}/analysis` returns. See docs/architecture/Frontend.md §5 and this
         *     task's `decisions` entry for the endpoint-shape rationale, and `analyse_history`'s own
         *     docstring (plus `app.signals.engine._weekly_through_bar_date`) for how Screen 1/Tide is
         *     itself recomputed per bar from only the weekly data available as of that bar's own
         *     calendar week -- not held fixed at today's value.
         *
         *     `ticker` is normalized to uppercase, matching the other `/api/stocks/*` routes. Malformed
         *     bars (NaN OHLC, see `app.signals.engine.drop_malformed_daily_bars`) are dropped from
         *     `daily_ohlcv` up front, same as `/analysis`. The full (untrimmed) daily history is always
         *     fetched first so every emitted point -- including ones near the start of the requested
         *     `range` -- has correct indicator warm-up context; `range` only controls which already-
         *     computed points are included in the response, not how much history feeds the computation.
         *     The last entry in `points` always matches `GET /api/stocks/{ticker}/analysis`'s
         *     `signal`/`confidence`/`indicators` for this same ticker at the same date, since it's
         *     produced from the exact same (untruncated) inputs.
         */
        get: operations["get_stock_indicator_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every watched ticker with its current signal
         * @description Every ticker on the watchlist, each annotated with its current BUY/SELL/HOLD signal
         *     and confidence by re-running the same Triple Screen signal engine
         *     `GET /api/stocks/{ticker}/analysis` uses (`app.signals.engine.analyse`,
         *     docs/Analyse.md §5) -- so "does the watchlist signal a buy" always agrees with what a
         *     direct lookup of that ticker's analysis page would say, with no second implementation of
         *     the buy check to drift out of sync.
         *
         *     `signal`/`confidence`/`confidence_band` are null together on an entry whose signal
         *     couldn't be computed right now (unknown/delisted ticker, insufficient history, or the
         *     data provider being unavailable) -- this endpoint never fails or drops an entry just
         *     because one watched ticker's data is temporarily/permanently unavailable; see this
         *     task's `decisions` entry. Ordered by `added_at` (oldest first), then `ticker` as a
         *     tiebreaker for same-instant adds, mirroring `GET /api/portfolio`'s deterministic
         *     ordering convention (`app.api.routers.portfolio._ordered_positions`).
         */
        get: operations["get_watchlist"];
        put?: never;
        /**
         * Add a ticker to the watchlist
         * @description Adds `ticker` to the watchlist. Adding a ticker that's already watched is a no-op:
         *     the existing entry (with its original `added_at`) is returned unchanged, still with
         *     `201`, rather than creating a duplicate row or rejecting with `409`/`422` -- see this
         *     task's `decisions` entry for the full rationale.
         *
         *     `signal`/`confidence`/`confidence_band` are always `null` in this response: annotation
         *     happens on read (`GET /api/watchlist`), not on write -- mirroring
         *     `POST /api/portfolio/positions`'s `current_price`/`unrealized_pnl_pct`
         *     null-on-write convention.
         */
        post: operations["add_watchlist_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a ticker from the watchlist
         * @description Removes `ticker` from the watchlist entirely. `ticker` is normalized to uppercase,
         *     matching every other `/api/watchlist` and `/api/stocks/*` route.
         */
        delete: operations["delete_watchlist_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Confidence
             * @description 0-100 weighted composite score (docs/Analyse.md §6). Not a statistical probability.
             */
            confidence: number;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70.
             * @enum {string}
             */
            confidence_band: "Low" | "Medium" | "High";
            /**
             * Confidence Breakdown
             * @description Per-component scores behind `confidence`, so the signal is auditable rather than a bare number.
             */
            confidence_breakdown: components["schemas"]["ConfidenceBreakdownItem"][];
            /** @description Latest-bar-only snapshot. For the same 7 indicator values (plus stochastic_k/force_index_2ema, which live under screens.wave here) as a historical time series across every bar instead, see GET /api/stocks/{ticker}/indicators. */
            indicators: components["schemas"]["Indicators"];
            screens: components["schemas"]["Screens"];
            /**
             * Signal
             * @enum {string}
             */
            signal: "BUY" | "SELL" | "HOLD";
            /** Ticker */
            ticker: string;
        };
        /** ConfidenceBreakdownItem */
        ConfidenceBreakdownItem: {
            /**
             * Component
             * @description One of the five weighted components from docs/Analyse.md §6, e.g. 'tide_alignment'.
             */
            component: string;
            /**
             * Score
             * @description How strongly this component supports the signal (0-1), before weighting.
             */
            score: number;
            /**
             * Weight
             * @description This component's fixed weight (0-1); all five weights sum to 1.0.
             */
            weight: number;
        };
        /** Equity */
        Equity: {
            /** Cash */
            cash: number;
            /**
             * Positions Value
             * @description Sum of quantity x current_price across all positions (mark-to-market, not cost basis).
             */
            positions_value: number;
            /**
             * Total
             * @description cash + positions_value.
             */
            total: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
            /**
             * Interval
             * @enum {string}
             */
            interval: "daily" | "weekly";
            /** Ticker */
            ticker: string;
        };
        /** IndicatorHistoryPoint */
        IndicatorHistoryPoint: {
            /**
             * Bear Power
             * @description Elder-Ray Bear Power = Low - EMA(13), for this bar.
             */
            bear_power: number;
            /**
             * Bull Power
             * @description Elder-Ray Bull Power = High - EMA(13), for this bar.
             */
            bull_power: number;
            /**
             * Confidence
             * @description Same 0-100 weighted composite score as AnalysisResponse.confidence, for this bar's signal. 0 whenever signal is HOLD, same convention as GET /api/stocks/{ticker}/analysis.
             */
            confidence: number;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70, for this bar's confidence.
             * @enum {string}
             */
            confidence_band: "Low" | "Medium" | "High";
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Ema 13
             * @description Same definition as AnalysisResponse.indicators.ema_13, for this bar.
             */
            ema_13: number;
            /**
             * Ema 26
             * @description Same definition as AnalysisResponse.indicators.ema_26, for this bar.
             */
            ema_26: number;
            /**
             * Force Index 2Ema
             * @description Force Index, 2-period EMA smoothing, same definition as WaveScreen.force_index_2ema, for this bar. Null for a bar still inside the indicator's warm-up window (needs ~2 prior bars) -- same warm-up-only caveat as stochastic_k above.
             */
            force_index_2ema?: number | null;
            /**
             * Macd Histogram
             * @description Same definition as AnalysisResponse.indicators.macd_histogram, for this bar.
             */
            macd_histogram: number;
            /**
             * Signal
             * @description BUY/SELL/HOLD as of this bar (docs/Analyse.md §5), computed from only this bar's own history -- never look-ahead from a later bar.
             * @enum {string}
             */
            signal: "BUY" | "SELL" | "HOLD";
            /**
             * Stochastic K
             * @description Stochastic %K (5,3,3), same definition as WaveScreen.stochastic_k, for this bar. Null for a bar still inside the indicator's warm-up window (needs ~11 prior bars) -- unlike WaveScreen.stochastic_k on GET /api/stocks/{ticker}/analysis, which is always non-null since /analysis only ever reports the latest bar, by definition never still warming up.
             */
            stochastic_k?: number | null;
        };
        /** IndicatorHistoryResponse */
        IndicatorHistoryResponse: {
            /**
             * Points
             * @description Oldest-first, one entry per daily bar in the requested range. The last entry always matches GET /api/stocks/{ticker}/analysis's signal/confidence/indicators for this same ticker (same as_of date, computed from the same inputs). Screen 1 (Tide) IS point-in-time recomputed per bar, from only the weekly data as-of that bar's own calendar week -- not held fixed at today's value (see the api-stocks-indicator-history task's decisions).
             */
            points: components["schemas"]["IndicatorHistoryPoint"][];
            /** Ticker */
            ticker: string;
        };
        /** Indicators */
        Indicators: {
            /**
             * Bear Power
             * @description Elder-Ray Bear Power = Low - EMA(13).
             */
            bear_power: number;
            /**
             * Bull Power
             * @description Elder-Ray Bull Power = High - EMA(13).
             */
            bull_power: number;
            /** Ema 13 */
            ema_13: number;
            /** Ema 26 */
            ema_26: number;
            /** Macd Histogram */
            macd_histogram: number;
        };
        /** OHLCVBar */
        OHLCVBar: {
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Volume */
            volume: number;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            equity: components["schemas"]["Equity"];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
        };
        /** PositionIn */
        PositionIn: {
            /**
             * Avg Cost Basis
             * @description Price paid per share for this lot. On merge with an existing position, this is blended into a quantity-weighted average, not overwritten. Must be a positive, finite number (Infinity/NaN are rejected).
             */
            avg_cost_basis: number;
            /**
             * Entry Date
             * Format: date
             * @description Date this lot was purchased. On merge with an existing position, the earlier of the two entry dates is kept.
             */
            entry_date: string;
            /**
             * Quantity
             * @description Number of shares being added. Must be a positive, finite number (Infinity/NaN are rejected) — this endpoint only adds to a position; use DELETE /api/portfolio/positions/{id} to remove one.
             */
            quantity: number;
            /**
             * Ticker
             * @description Stock ticker symbol, normalized to uppercase (leading/trailing whitespace is stripped). Adding a ticker that's already held merges into the existing position (quantity-weighted average cost basis) rather than creating a duplicate row — see the api-portfolio-add-position task's decisions.
             */
            ticker: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Avg Cost Basis */
            avg_cost_basis: number;
            /**
             * Current Price
             * @description Null only if the latest price fetch for this ticker failed.
             */
            current_price?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Id */
            id: string;
            /** Quantity */
            quantity: number;
            /** Ticker */
            ticker: string;
            /**
             * Unrealized Pnl Pct
             * @description (current_price - avg_cost_basis) / avg_cost_basis, as a percentage. Null under the same condition as current_price.
             */
            unrealized_pnl_pct?: number | null;
        };
        /** RiskPosition */
        RiskPosition: {
            /**
             * Exit Flags
             * @description Risk-driven exit reasons, e.g. 'stop_hit', 'tide_flipped_bearish' (docs/Analyse.md §7). Independent of this stock's fresh entry signal — can be non-empty even when /analysis says HOLD.
             */
            exit_flags: string[];
            /** Id */
            id: string;
            /**
             * Position Risk Pct
             * @description Fraction of current account equity lost if this position hits its protective_stop (the 2% rule).
             */
            position_risk_pct: number;
            /**
             * Protective Stop
             * @description Recent swing low minus a volatility buffer (SafeZone concept, docs/Analyse.md §7).
             */
            protective_stop: number;
            /** Ticker */
            ticker: string;
            /** Two Percent Rule Breached */
            two_percent_rule_breached: boolean;
        };
        /** RiskResponse */
        RiskResponse: {
            /** Positions */
            positions: components["schemas"]["RiskPosition"][];
            /** Six Percent Rule Breached */
            six_percent_rule_breached: boolean;
            /**
             * Total Open Risk Pct
             * @description Sum of position_risk_pct across all positions (the 6% rule).
             */
            total_open_risk_pct: number;
        };
        /** Screens */
        Screens: {
            /**
             * Impulse
             * @description Impulse System gate (docs/Analyse.md §3). RED blocks fresh BUY signals, GREEN blocks fresh SELL signals.
             * @enum {string}
             */
            impulse: "GREEN" | "RED" | "BLUE";
            tide: components["schemas"]["TideScreen"];
            trigger: components["schemas"]["TriggerScreen"];
            wave: components["schemas"]["WaveScreen"];
        };
        /** TideScreen */
        TideScreen: {
            /**
             * Trend
             * @description Screen 1 output (docs/Analyse.md §2). NEUTRAL when weekly MACD-Histogram slope and the 13/26-week EMA relationship disagree.
             * @enum {string}
             */
            trend: "BULLISH" | "BEARISH" | "NEUTRAL";
            /**
             * Weekly Macd Histogram Slope
             * @enum {string}
             */
            weekly_macd_histogram_slope: "rising" | "falling" | "flat";
        };
        /** TriggerScreen */
        TriggerScreen: {
            /**
             * Fired
             * @description Whether Screen 3 confirmed price has resumed the tide's direction.
             */
            fired: boolean;
            /**
             * Reference
             * @description Which trigger rule fired, e.g. 'close_above_prior_high'.
             */
            reference: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistItemIn */
        WatchlistItemIn: {
            /**
             * Ticker
             * @description Stock ticker symbol to watch, normalized to uppercase (leading/trailing whitespace is stripped). Adding a ticker already on the watchlist is a no-op that returns the existing entry unchanged (original added_at kept) rather than creating a duplicate row or rejecting with 409/422 -- see the api-watchlist task's `decisions`.
             */
            ticker: string;
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /**
             * Added At
             * Format: date-time
             * @description When this ticker was added to the watchlist (UTC).
             */
            added_at: string;
            /**
             * Confidence
             * @description Same 0-100 weighted composite score as AnalysisResponse.confidence. Null under the same condition as `signal`.
             */
            confidence?: number | null;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70. Null under the same condition as `signal`.
             */
            confidence_band?: ("Low" | "Medium" | "High") | null;
            /**
             * Signal
             * @description BUY/SELL/HOLD from the exact same Triple Screen signal engine GET /api/stocks/{ticker}/analysis uses (docs/Analyse.md §5) -- not a separately-implemented buy check. Null only if the signal couldn't be computed for this ticker right now (unknown/delisted ticker, insufficient history, or the data provider being unavailable), mirroring PositionOut's current_price null-on-failure pattern -- see the api-watchlist task's `decisions`.
             */
            signal?: ("BUY" | "SELL" | "HOLD") | null;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /**
             * Items
             * @description Every watched ticker, ordered by when it was added (oldest first).
             */
            items: components["schemas"]["WatchlistItemOut"][];
        };
        /** WaveScreen */
        WaveScreen: {
            /**
             * Force Index 2Ema
             * @description Force Index, 2-period EMA smoothing (entry-timing variant, not the 13-period trend-confirmation one).
             */
            force_index_2ema: number;
            /**
             * State
             * @description Human-readable wave state, e.g. 'OVERSOLD_PULLBACK' — evaluated against the tide direction, not in isolation (docs/Analyse.md §2).
             */
            state: string;
            /**
             * Stochastic K
             * @description Stochastic %K (5,3,3). Values below 30 are oversold, above 70 are overbought (docs/Analyse.md §4).
             */
            stochastic_k: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    add_position: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: ordinary request-body validation failure (FastAPI's standard HTTPValidationError — `detail` is a list of per-field errors), or merging with an existing position would produce a quantity/avg_cost_basis too large to represent (`detail` is a single string, ErrorDetail). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    delete_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_risk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
        };
    };
    get_stock_analysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Insufficient history to compute weekly indicators */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_stock_history: {
        parameters: {
            query?: {
                /** @description Lookback window: '<N>d' | '<N>w' | '<N>m' | '<N>y' (e.g. '1y', '6m', '90d'), or 'max' for full available history. Trimmed from the most recent bar actually returned, not from today's date. */
                range?: string;
                interval?: "daily" | "weekly";
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: `range` doesn't match the accepted pattern (FastAPI's standard HTTPValidationError — `detail` is a list of per-field errors), or the requested weekly interval has fewer than 26 weeks of history (`detail` is a single string, ErrorDetail) — same dual-shape pattern as `POST /api/portfolio/positions`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_stock_indicator_history: {
        parameters: {
            query?: {
                /** @description Same lookback-window grammar as GET /api/stocks/{ticker}/history's `range`: '<N>d' | '<N>w' | '<N>m' | '<N>y' (e.g. '1y', '6m', '90d'), or 'max' for full available history. Trimmed from the most recent bar actually returned, not from today's date. Daily bars only -- unlike /history, this endpoint has no `interval` param, since every indicator/Screen it computes (docs/Analyse.md §4) is itself daily-cadence; see this task's `decisions` entry. */
                range?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorHistoryResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: `range` doesn't match the accepted pattern (FastAPI's standard HTTPValidationError -- `detail` is a list of per-field errors), or the ticker has fewer than 26 weeks of weekly history to compute Screen 1's Tide (`detail` is a single string, ErrorDetail) -- same dual-shape pattern as `GET /api/stocks/{ticker}/history`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    add_watchlist_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticker not on the watchlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
