/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current positions and account equity
         * @description All held positions plus account equity (cash + mark-to-market positions value).
         *     `current_price`/`unrealized_pnl_pct` on each position are enriched from the market
         *     data cache and are null only if a price fetch for that ticker has failed. A position
         *     whose price couldn't be fetched contributes nothing to `equity.positions_value`
         *     (it can't be marked to market) rather than falling back to cost basis — see this
         *     task's `decisions` entry. The fetch-and-degrade-gracefully loop itself lives in
         *     `app.portfolio.pricing` (shared with GET /api/portfolio/risk) — see the
         *     api-portfolio-risk task's `decisions` entry.
         *
         *     `signal`/`confidence`/`confidence_band` on each position come from the exact same
         *     Triple Screen signal engine (`app.signals.engine.analyse`, docs/Analyse.md §5) GET
         *     /api/stocks/{ticker}/analysis and GET /api/watchlist use -- no second, divergent signal
         *     computation. Null together on a position whose signal couldn't be computed right now
         *     (its price fetch already failed, the separate weekly-history fetch the signal engine
         *     needs failed, or the latest daily bar has a valid close but NaN open/high/low -- the
         *     signal fields go null rather than silently reflecting yesterday's bar while
         *     `current_price` reflects today's), mirroring `current_price`'s own null-on-failure
         *     convention and WatchlistItemOut's identical precedent -- the position itself is still
         *     returned, never dropped or 500'd, just as a price-fetch failure never drops it -- see
         *     `_compute_position_signal`'s docstring and the api-portfolio-position-signal task's
         *     `decisions` entry.
         */
        get: operations["get_portfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/closed-trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get closed trades (trade history) with A-trade grades
         * @description Every row in the `closed_trades` table (docs/Analyse.md §7's trade-history/ledger
         *     table, populated by `DELETE /api/portfolio/positions/{id}`), most recently exited first
         *     (`exit_date` descending, `id` descending as a same-day tiebreaker -- mirrors
         *     `_ordered_positions`'s own deterministic-ordering rationale, just newest-first here since
         *     trade history is read for recency rather than portfolio composition).
         *
         *     Each trade is annotated with its `buy_grade_pct`/`sell_grade_pct`/`trade_grade_pct`
         *     (Elder ch. 55 "Is This an A-Trade?", docs/Analyse.md §7 / docs/ideas.md ch. 55) --
         *     `app.portfolio.grading.grade_closed_trade`, sourced from the ticker's daily OHLCV (that
         *     day's own high/low) and the entry day's Autoenvelope/channel bounds (the same computation
         *     `AnalysisResponse.indicators.channel_upper`/`channel_lower` expose). Grading a trade is
         *     preferred over judging it by raw P&L alone, since it accounts for how much was
         *     realistically available to capture that day/that channel, not just what was captured.
         *
         *     Grading never fails the request: a ticker whose current daily-history fetch fails, or a
         *     trade whose entry/exit date isn't an exact row in that history (e.g. it predates the
         *     fetched history, or falls inside the Autoenvelope's ~100-bar warm-up window), simply gets
         *     null grade fields on an otherwise fully-populated row -- see `_grade_closed_trades`'s
         *     docstring.
         */
        get: operations["get_closed_trades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add or update a position
         * @description Creates a position from manual entry / CSV-import data. If a position for this ticker
         *     already exists it is merged rather than duplicated: quantities are summed and
         *     avg_cost_basis becomes the quantity-weighted average of the existing and incoming cost
         *     bases (mirrors how a brokerage averages up/down a position instead of tracking separate
         *     lots) — see the api-portfolio-add-position task's `decisions` for the full rationale and
         *     the rejected reject-with-409 alternative. entry_date keeps the earlier of the two dates.
         *     `current_price`/`unrealized_pnl_pct` are always null here: price enrichment happens on
         *     read (GET /api/portfolio), not on write, and isn't available until the data-cache task
         *     lands. `signal`/`confidence`/`confidence_band` are always null here too, for the same
         *     reason -- signal annotation happens on read (GET /api/portfolio), not on write, mirroring
         *     POST /api/watchlist's identical null-on-write convention for the same fields.
         */
        post: operations["add_position"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a position, recording it as a closed trade
         * @description Removes a position entirely. There is no partial-quantity reduction endpoint --
         *     reducing a position means deleting and re-adding it with the new quantity.
         *
         *     Also records a `closed_trades` row (ticker, quantity, entry price/date, exit price/date,
         *     realized P&L, exit_reason) -- the trade-history/ledger this app previously had no model
         *     for at all -- feeding both GET /api/portfolio/risk's realized-losses-this-month component
         *     of the 6% Rule (docs/Analyse.md §7) and, longer-term, the backend-trade-grading task's
         *     buy/sell/trade-grade formulas plus a future trade-journal frontend page. `exit_price` is
         *     today's latest close for this ticker, fetched the same way `current_price` is everywhere
         *     else in this router (`app.portfolio.pricing.latest_close`) -- not a caller-supplied price,
         *     since this app already treats "current market price" as authoritative for mark-to-market
         *     elsewhere rather than trusting a client-supplied number. `realized_pnl` is
         *     `quantity * (exit_price - avg_cost_basis)`. If that price fetch fails (unknown/delisted
         *     ticker, provider unavailable), the position is still deleted -- a data-provider outage
         *     must never block removing a position -- but no `closed_trades` row is recorded, since
         *     there's no way to compute a realized P&L without an exit price; see the
         *     backend-trade-history-table task's `decisions` entry for the full rationale (including why
         *     this endpoint doesn't accept a caller-supplied `exit_price` instead).
         */
        delete: operations["delete_position"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the 2%/6% rule evaluation and per-position exit flags
         * @description Per-position protective stop, 2%-rule risk, and exit flags, plus the portfolio-wide
         *     6%-rule total (docs/Analyse.md §7). `exit_flags` can be non-empty even when the
         *     corresponding stock's fresh technical signal is HOLD — risk-driven exits are
         *     independent of entry-signal logic by design.
         *
         *     `total_open_risk_pct` is the book's actual two-part 6% Rule total (docs/Analyse.md §7, per
         *     docs/ideas.md's ch. 51 cross-check): this calendar month's realized losses
         *     (`realized_losses_this_month_pct`, from the `closed_trades` table `DELETE
         *     /api/portfolio/positions/{id}` populates) plus current open-position risk (`app.portfolio
         *     .risk.total_open_risk_pct`, summed over positions with a known stop) -- see the
         *     backend-trade-history-table task's `decisions` entry for why the field keeps this name
         *     despite now covering both halves.
         *
         *     A position is silently excluded from `positions` (and so from the open-risk half of
         *     `total_open_risk_pct` -- see `app.portfolio.risk.total_open_risk_pct`) whenever its risk
         *     can't be computed at all: its current price
         *     couldn't be fetched (same degrade-gracefully rule as GET /api/portfolio — see this
         *     task's `decisions` entry), its daily history has fewer than 2 rows once any malformed
         *     bar is dropped (the minimum `evaluate_exit_flags` needs to test today's close against
         *     yesterday's stop), its weekly history couldn't be fetched, or
         *     `protective_stop`/`evaluate_exit_flags` raised for a malformed frame. `RiskPosition`'s
         *     fields are all non-nullable, so a position that can't be fully evaluated has no partial
         *     representation in this schema — see this task's `decisions` entry.
         *
         *     `e.daily_ohlcv` is passed through `app.signals.engine.drop_malformed_daily_bars` before
         *     `protective_stop`/`evaluate_exit_flags` ever see it — mirroring GET
         *     /api/stocks/{ticker}/analysis's identical filtering — so a malformed bar anywhere in a
         *     position's history can't silently suppress an exit flag via a NaN comparison quietly
         *     evaluating False. Called here with `require_full_ohlc_on_latest_bar=False`, unlike GET
         *     /api/stocks/{ticker}/analysis's default-`True` call: the *latest* bar is dropped only if
         *     its own `close` is NaN, matching `app.portfolio.pricing.latest_close`'s own close-only
         *     validity rule for that exact bar (which is what `position.current_price` was derived
         *     from), rather than also requiring open/high/low there — a shape `latest_close` doesn't
         *     guard against, and one this pipeline's own downstream reads (`evaluate_exit_flags` and
         *     everything it calls) never touch for the latest bar anyway. Using the stricter default here
         *     would silently drop a real latest bar whose close is valid but whose open/high/low haven't
         *     settled yet, desyncing `position.current_price` from `daily_ohlcv`'s last row and making
         *     `evaluate_exit_flags` test yesterday's close against today's stop instead of today's — see
         *     the api-stocks-analysis-nullable-indicators-followups task's `decisions` entry for the full
         *     reasoning and the regression this reconciles.
         */
        get: operations["get_portfolio_risk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Triple Screen signal, confidence, and indicator breakdown
         * @description Runs the full Triple Screen evaluation (tide, wave, trigger, Impulse gate) and the
         *     weighted confidence score for `ticker` (docs/Analyse.md §2-6). `confidence_breakdown`
         *     exposes the per-component scores so the signal is auditable, not just a bare number.
         *
         *     `ticker` is normalized to uppercase (mirrors `POST /api/portfolio/positions`'s handling
         *     of the same field) before being passed to the data provider and echoed back in the
         *     response. Daily and weekly OHLCV are fetched via the SQLite-backed cache
         *     (`app.data.cache.CachedDataProvider`, docs/architecture/Backend.md §7); the weekly fetch
         *     is what actually enforces the <26-week-history -> 422 rule
         *     (`app.data.yfinance_provider.YFinanceProvider._MIN_WEEKLY_BARS`) -- this handler adds no
         *     separate minimum-history check of its own, matching `app.signals.engine.analyse`'s own
         *     documented degrade-gracefully-to-HOLD behavior for a short/empty daily series (see this
         *     task's `decisions` entry).
         *
         *     `daily_ohlcv` has any malformed bar (NaN open/high/low/close -- a real observed
         *     unsettled-latest-bar condition) dropped via `app.signals.engine.drop_malformed_daily_bars`
         *     before `as_of` is derived from it, so `as_of` reflects the same freshest *real* bar that
         *     actually drove `analyse()` -- not a malformed bar `analyse()` itself excludes internally
         *     anyway (see that function's own docstring and this task's `decisions` entry).
         */
        get: operations["get_stock_analysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OHLCV price history
         * @description Raw OHLCV bars for charting, served from the SQLite cache (docs/architecture/Backend.md §7)
         *     and backfilled from yfinance/Stooq on a cache miss. Weekly bars are yfinance's native
         *     weekly interval, not a manual resample of daily bars, per docs/Analyse.md §9.
         *
         *     `ticker` is normalized to uppercase, matching `GET /api/stocks/{ticker}/analysis` and
         *     `POST /api/portfolio/positions`. Only the interval actually requested is fetched (unlike
         *     `/analysis`, which always needs both) -- so a `weekly`-interval request is the only way
         *     this endpoint can itself raise the same <26-week `InsufficientHistoryError` -> 422 that
         *     `/analysis`'s weekly fetch enforces (`app.data.yfinance_provider.YFinanceProvider._MIN_WEEKLY_BARS`);
         *     see this task's `decisions` entry for why that's surfaced here too rather than only for
         *     computed indicators.
         */
        get: operations["get_stock_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical indicator values and the resulting signal for each daily bar
         * @description Re-runs the Triple Screen signal engine (`app.signals.engine.analyse`, via
         *     `app.signals.engine.analyse_history`) once per daily bar in the requested range, each time
         *     using only that bar's own history (no look-ahead) -- so the frontend can plot indicator
         *     lines and BUY/SELL/HOLD markers over time, instead of only the latest-bar snapshot
         *     `GET /api/stocks/{ticker}/analysis` returns. See docs/architecture/Frontend.md §5 and this
         *     task's `decisions` entry for the endpoint-shape rationale, and `analyse_history`'s own
         *     docstring (plus `app.signals.engine._weekly_through_bar_date`) for how Screen 1/Tide is
         *     itself recomputed per bar from only the weekly data available as of that bar's own
         *     calendar week -- not held fixed at today's value.
         *
         *     `ticker` is normalized to uppercase, matching the other `/api/stocks/*` routes. Malformed
         *     bars (NaN OHLC, see `app.signals.engine.drop_malformed_daily_bars`) are dropped from
         *     `daily_ohlcv` up front, same as `/analysis`. The full (untrimmed) daily history is always
         *     fetched first so every emitted point -- including ones near the start of the requested
         *     `range` -- has correct indicator warm-up context; `range` only controls which already-
         *     computed points are included in the response, not how much history feeds the computation.
         *     The last entry in `points` always matches `GET /api/stocks/{ticker}/analysis`'s
         *     `signal`/`confidence`/`indicators` for this same ticker at the same date, since it's
         *     produced from the exact same (untruncated) inputs.
         */
        get: operations["get_stock_indicator_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every watched ticker with its current signal
         * @description Every ticker on the watchlist, each annotated with its current BUY/SELL/HOLD signal
         *     and confidence by re-running the same Triple Screen signal engine
         *     `GET /api/stocks/{ticker}/analysis` uses (`app.signals.engine.analyse`,
         *     docs/Analyse.md §5) -- so "does the watchlist signal a buy" always agrees with what a
         *     direct lookup of that ticker's analysis page would say, with no second implementation of
         *     the buy check to drift out of sync.
         *
         *     `signal`/`confidence`/`confidence_band` are null together on an entry whose signal
         *     couldn't be computed right now (unknown/delisted ticker, insufficient history, or the
         *     data provider being unavailable) -- this endpoint never fails or drops an entry just
         *     because one watched ticker's data is temporarily/permanently unavailable; see this
         *     task's `decisions` entry. Ordered by `added_at` (oldest first), then `ticker` as a
         *     tiebreaker for same-instant adds, mirroring `GET /api/portfolio`'s deterministic
         *     ordering convention (`app.api.routers.portfolio._ordered_positions`).
         */
        get: operations["get_watchlist"];
        put?: never;
        /**
         * Add a ticker to the watchlist
         * @description Adds `ticker` to the watchlist. Adding a ticker that's already watched is a no-op:
         *     the existing entry (with its original `added_at`) is returned unchanged, still with
         *     `201`, rather than creating a duplicate row or rejecting with `409`/`422` -- see this
         *     task's `decisions` entry for the full rationale.
         *
         *     `signal`/`confidence`/`confidence_band` are always `null` in this response: annotation
         *     happens on read (`GET /api/watchlist`), not on write -- mirroring
         *     `POST /api/portfolio/positions`'s `current_price`/`unrealized_pnl_pct`
         *     null-on-write convention.
         */
        post: operations["add_watchlist_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a ticker from the watchlist
         * @description Removes `ticker` from the watchlist entirely. `ticker` is normalized to uppercase,
         *     matching every other `/api/watchlist` and `/api/stocks/*` route.
         */
        delete: operations["delete_watchlist_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Confidence
             * @description 0-100 weighted composite score (docs/Analyse.md §6). Not a statistical probability.
             */
            confidence: number;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70.
             * @enum {string}
             */
            confidence_band: "Low" | "Medium" | "High";
            /**
             * Confidence Breakdown
             * @description Per-component scores behind `confidence`, so the signal is auditable rather than a bare number.
             */
            confidence_breakdown: components["schemas"]["ConfidenceBreakdownItem"][];
            /** @description The most recent qualifying MACD-Histogram/Stochastic/RSI divergence detected between price's own swing points and each indicator's value at those dates (docs/ideas.md, Elder ch. 15/23/26/27) -- null if none currently qualifies. When more than one indicator qualifies with the same second_extreme_date (common, since all three are checked against the same price swing points), MACD-Histogram wins, then Stochastic, then RSI. Detection + exposure only -- not wired into signal/confidence_breakdown (see the backend-divergence-detection task's decisions). */
            divergence: components["schemas"]["DivergenceOut"] | null;
            /** @description Latest-bar-only snapshot. For the same 8 indicator values (plus stochastic_k/force_index_2ema, which live under screens.wave here) as a historical time series across every bar instead, see GET /api/stocks/{ticker}/indicators. */
            indicators: components["schemas"]["Indicators"];
            screens: components["schemas"]["Screens"];
            /**
             * Signal
             * @enum {string}
             */
            signal: "BUY" | "SELL" | "HOLD";
            /**
             * Support Resistance Zones
             * @description Horizontal support/resistance zones detected from swing-point clustering over the ticker's full available daily history (docs/ideas.md, Elder ch. 18) -- up to the 15 strongest by strength_score, descending. Not currently wired into signal/confidence computation or protective_stop -- informational context only (see the backend-support-resistance task's decisions for why tightening protective_stop near a zone is an explicit, separate follow-up).
             */
            support_resistance_zones: components["schemas"]["SupportResistanceZone"][];
            /** Ticker */
            ticker: string;
        };
        /** ClosedTradeOut */
        ClosedTradeOut: {
            /**
             * Buy Grade Pct
             * @description (entry day's high - entry_price) / (entry day's high - entry day's low), as a percentage -- how close to the entry day's low the buy actually was (Elder ch. 55 'Is This an A-Trade?', docs/Analyse.md §7 / docs/ideas.md ch. 55). >50% is 'very good'. Null whenever the entry day's own OHLC can't be found in the ticker's currently-fetchable daily history (e.g. entry_date predates that history, the fetch itself failed, or that bar was dropped as malformed) or the entry day had a zero/negative trading range -- see app.portfolio.grading.grade_closed_trade.
             */
            buy_grade_pct?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Price */
            entry_price: number;
            /**
             * Exit Date
             * Format: date
             */
            exit_date: string;
            /** Exit Price */
            exit_price: number;
            /**
             * Exit Reason
             * @description Why this position was closed, from Elder's own taxonomy (docs/Analyse.md §7 / docs/ideas.md's ch. 51 cross-check) plus this app's own 'unspecified' default for a trade closed with no explicit reason supplied -- see DELETE /api/portfolio/positions/{id}.
             * @enum {string}
             */
            exit_reason: "target_hit" | "stop_hit" | "reached_value_zone" | "going_nowhere" | "starting_to_turn" | "couldnt_stand_the_pain" | "recognized_junk_trade_after_entry" | "unspecified";
            /** Id */
            id: string;
            /** Quantity */
            quantity: number;
            /**
             * Realized Pnl
             * @description quantity * (exit_price - entry_price) -- see DELETE /api/portfolio/positions/{id} for how this row is recorded.
             */
            realized_pnl: number;
            /**
             * Sell Grade Pct
             * @description (exit_price - exit day's low) / (exit day's high - exit day's low), as a percentage -- how close to the exit day's high the sell actually was. >50% is 'very good'. Null under the same conditions as buy_grade_pct, evaluated for the exit day instead.
             */
            sell_grade_pct?: number | null;
            /** Ticker */
            ticker: string;
            /**
             * Trade Grade Pct
             * @description (exit_price - entry_price) / (channel_upper - channel_lower, measured on entry_date), as a percentage -- the trade's actual gain as a fraction of the entry day's Autoenvelope/channel height (docs/Analyse.md §4, same channel AnalysisResponse.indicators.channel_upper/channel_lower expose). >=30% capture is an 'A' trade, ~10% a 'C' trade. Null whenever the entry day's channel bounds aren't available -- the ticker's fetched daily history doesn't reach back to entry_date, or entry_date falls inside the Autoenvelope's own ~100-bar warm-up window.
             */
            trade_grade_pct?: number | null;
        };
        /** ClosedTradesResponse */
        ClosedTradesResponse: {
            /**
             * Items
             * @description Every closed trade (the docs/Analyse.md §7 trade-history/ledger table), most recently exited first.
             */
            items: components["schemas"]["ClosedTradeOut"][];
        };
        /** ConfidenceBreakdownItem */
        ConfidenceBreakdownItem: {
            /**
             * Component
             * @description One of the five weighted components from docs/Analyse.md §6, e.g. 'tide_alignment'.
             */
            component: string;
            /**
             * Score
             * @description How strongly this component supports the signal (0-1), before weighting.
             */
            score: number;
            /**
             * Weight
             * @description This component's fixed weight (0-1); all five weights sum to 1.0.
             */
            weight: number;
        };
        /** DivergenceOut */
        DivergenceOut: {
            /**
             * Aborted
             * @description 'Hound of the Baskervilles' (docs/ideas.md): whether price has, as of as_of, already ignored this divergence -- continued making new lows past second_extreme_price despite a bullish divergence, or new highs past it despite a bearish one -- which Elder treats as a strong continuation signal in the opposite direction (his one explicit stop-and-reverse case), not a failed signal to discard.
             */
            aborted: boolean;
            /**
             * Bars Apart
             * @description Trading-day spacing between the two extremes. Always between 20 and 40 inclusive (Kerry Lovvorn's empirical spacing filter, docs/ideas.md) -- a closer-together or further-apart pair is never reported as a divergence at all.
             */
            bars_apart: number;
            /**
             * Beyond Reference Line
             * @description Whether this divergence is at its textbook strongest for Stochastic/RSI: the first extreme beyond the oscillator's own overbought/oversold reference line (30/70) and the second back inside it. Informational only, never a requirement. Null for 'macd_histogram', where this concept doesn't apply.
             */
            beyond_reference_line: boolean | null;
            /**
             * Centerline Crossed
             * @description Whether MACD-Histogram crossed its own zero centerline between the two extremes -- 'an absolute must for a true divergence' per the book. Always true when indicator is 'macd_histogram' (a non-crossing pair is never reported as a divergence at all, so this is never false here); null for 'stochastic'/'rsi', which have no such requirement.
             */
            centerline_crossed: boolean | null;
            /**
             * First Extreme Date
             * Format: date
             * @description Date of the earlier of the two compared price swing points.
             */
            first_extreme_date: string;
            /**
             * First Extreme Indicator Value
             * @description indicator's own value at first_extreme_date -- not necessarily a local extreme of the indicator itself, just its reading on the day price made this swing point (docs/ideas.md's own phrasing: 'the indicator's value at the prior comparable swing extreme').
             */
            first_extreme_indicator_value: number;
            /**
             * First Extreme Price
             * @description Price (close) at first_extreme_date.
             */
            first_extreme_price: number;
            /**
             * Indicator
             * @description Which oscillator this divergence was detected against -- MACD-Histogram (the book's usual choice, and the only one of the three with a centerline-crossing requirement), Stochastic %K, or RSI.
             * @enum {string}
             */
            indicator: "macd_histogram" | "stochastic" | "rsi";
            /**
             * Kind
             * @description Which way the divergence points -- 'bullish' from two successive price swing LOWS (a potential buy setup), 'bearish' from two successive swing HIGHS (a potential sell setup). Elder ch. 15/23/26/27, docs/ideas.md.
             * @enum {string}
             */
            kind: "bullish" | "bearish";
            /**
             * Second Extreme Date
             * Format: date
             * @description Date of the later of the two compared price swing points -- always the more recent, more extreme price swing (a new high for bearish, a new low for bullish) with a shallower indicator reading than first_extreme_indicator_value.
             */
            second_extreme_date: string;
            /**
             * Second Extreme Indicator Value
             * @description indicator's own value at second_extreme_date.
             */
            second_extreme_indicator_value: number;
            /**
             * Second Extreme Price
             * @description Price (close) at second_extreme_date.
             */
            second_extreme_price: number;
        };
        /** Equity */
        Equity: {
            /** Cash */
            cash: number;
            /**
             * Positions Value
             * @description Sum of quantity x current_price across all positions (mark-to-market, not cost basis).
             */
            positions_value: number;
            /**
             * Total
             * @description cash + positions_value.
             */
            total: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /**
         * ExitReason
         * @description Why a position was closed, per Elder's own taxonomy (docs/ideas.md's ch. 51 cross-check;
         *     docs/Analyse.md §7) -- recorded per row in ``ClosedTradeORM`` (app/db/models.py) so the
         *     future ``backend-trade-grading`` task's buy/sell/trade-grade formulas and a trade-journal
         *     frontend page have this to work with, in addition to this task's own use (the 6% Rule's
         *     realized-losses-this-month component, ``app.portfolio.risk.realized_losses_pct``).
         *
         *     ``UNSPECIFIED`` is not one of Elder's own tags -- it's this app's own default for a trade
         *     closed via ``DELETE /api/portfolio/positions/{id}`` without an explicit ``exit_reason``
         *     query param, since that endpoint has no way to *know* why the user is closing the position
         *     unless they say so (there's no target-price/stop-order concept tracked anywhere in this
         *     app to infer it from) -- see the backend-trade-history-table task's `decisions` entry.
         * @enum {string}
         */
        ExitReason: "target_hit" | "stop_hit" | "reached_value_zone" | "going_nowhere" | "starting_to_turn" | "couldnt_stand_the_pain" | "recognized_junk_trade_after_entry" | "unspecified";
        /** FalseBreakoutOut */
        FalseBreakoutOut: {
            /**
             * Breakout Date
             * Format: date
             * @description First date price closed beyond the zone.
             */
            breakout_date: string;
            /**
             * Direction
             * @description Which way price broke before failing back inside the zone -- 'up' through the upper edge, 'down' through the lower edge.
             * @enum {string}
             */
            direction: "up" | "down";
            /**
             * Extreme Price
             * @description The failed move's own extreme reached between breakout_date and reentry_date (the highest high for an 'up' false breakout, the lowest low for 'down') -- the book's explicit stop-placement reference: place a stop near this extreme, not further out.
             */
            extreme_price: number;
            /**
             * Reentry Date
             * Format: date
             * @description First subsequent date price closed back inside [lower, upper] -- what confirms the breakout was false, per docs/ideas.md's Elder ch. 18 note.
             */
            reentry_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
            /**
             * Interval
             * @enum {string}
             */
            interval: "daily" | "weekly";
            /** Ticker */
            ticker: string;
        };
        /** IndicatorHistoryPoint */
        IndicatorHistoryPoint: {
            /**
             * Bear Power
             * @description Elder-Ray Bear Power = Low - EMA(13), for this bar.
             */
            bear_power: number;
            /**
             * Bull Power
             * @description Elder-Ray Bull Power = High - EMA(13), for this bar.
             */
            bull_power: number;
            /**
             * Channel Lower
             * @description Same definition as AnalysisResponse.indicators.channel_lower, for this bar. Null under the same condition as channel_upper.
             */
            channel_lower?: number | null;
            /**
             * Channel Upper
             * @description Same definition as AnalysisResponse.indicators.channel_upper, for this bar. Null for a bar still inside the Autoenvelope deviation-average's ~100-bar warm-up window -- a far longer warm-up than stochastic_k/force_index_2ema above, so this is null across a much larger leading span of a long `range` (e.g. `range=max`) than either of those.
             */
            channel_upper?: number | null;
            /**
             * Confidence
             * @description Same 0-100 weighted composite score as AnalysisResponse.confidence, for this bar's signal. 0 whenever signal is HOLD, same convention as GET /api/stocks/{ticker}/analysis.
             */
            confidence: number;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70, for this bar's confidence.
             * @enum {string}
             */
            confidence_band: "Low" | "Medium" | "High";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** @description Same definition as AnalysisResponse.divergence, using only swing points confirmable from data available through this bar (no look-ahead) -- so this can differ from a later bar's divergence at the same underlying extreme dates once more history confirms a swing point AnalysisResponse.divergence. */
            divergence?: components["schemas"]["DivergenceOut"] | null;
            /**
             * Ema 13
             * @description Same definition as AnalysisResponse.indicators.ema_13, for this bar.
             */
            ema_13: number;
            /**
             * Ema 26
             * @description Same definition as AnalysisResponse.indicators.ema_26, for this bar.
             */
            ema_26: number;
            /**
             * Force Index 2Ema
             * @description Force Index, 2-period EMA smoothing, same definition as WaveScreen.force_index_2ema, for this bar. Null for a bar still inside the indicator's warm-up window (needs ~2 prior bars) -- same warm-up-only caveat as stochastic_k above.
             */
            force_index_2ema?: number | null;
            /**
             * Macd Histogram
             * @description Same definition as AnalysisResponse.indicators.macd_histogram, for this bar.
             */
            macd_histogram: number;
            /**
             * Rsi
             * @description Same definition as AnalysisResponse.indicators.rsi, for this bar. Null for a bar still inside the indicator's 9-day warm-up window -- same warm-up-only caveat as stochastic_k/force_index_2ema above, though with a shorter (9-bar) window than either.
             */
            rsi?: number | null;
            /**
             * Signal
             * @description BUY/SELL/HOLD as of this bar (docs/Analyse.md §5), computed from only this bar's own history -- never look-ahead from a later bar.
             * @enum {string}
             */
            signal: "BUY" | "SELL" | "HOLD";
            /**
             * Stochastic K
             * @description Stochastic %K (5,3,3), same definition as WaveScreen.stochastic_k, for this bar. Null for a bar still inside the indicator's warm-up window (needs (k_period - 1) + (smooth - 1) prior bars -- 6 with the current defaults, k_period=5/smooth=3) -- unlike WaveScreen.stochastic_k on GET /api/stocks/{ticker}/analysis, which is always non-null since /analysis only ever reports the latest bar, by definition never still warming up.
             */
            stochastic_k?: number | null;
        };
        /** IndicatorHistoryResponse */
        IndicatorHistoryResponse: {
            /**
             * Points
             * @description Oldest-first, one entry per daily bar in the requested range. The last entry always matches GET /api/stocks/{ticker}/analysis's signal/confidence/indicators for this same ticker (same as_of date, computed from the same inputs). Screen 1 (Tide) IS point-in-time recomputed per bar, from only the weekly data as-of that bar's own calendar week -- not held fixed at today's value (see the api-stocks-indicator-history task's decisions).
             */
            points: components["schemas"]["IndicatorHistoryPoint"][];
            /** Ticker */
            ticker: string;
        };
        /** Indicators */
        Indicators: {
            /**
             * Bear Power
             * @description Elder-Ray Bear Power = Low - EMA(13).
             */
            bear_power: number;
            /**
             * Bull Power
             * @description Elder-Ray Bull Power = High - EMA(13).
             */
            bull_power: number;
            /**
             * Channel Lower
             * @description Lower Autoenvelope/channel band, same definition/source/warm-up as `channel_upper` mirrored to `mid * (1 - avg_pct)`.
             */
            channel_lower?: number | null;
            /**
             * Channel Upper
             * @description Upper Autoenvelope/channel band (docs/Analyse.md §4: 'EMA 13 ± avg % deviation') -- `app.indicators.autoenvelope.autoenvelope`'s `mid * (1 + avg_pct)`, where `mid` is this same response's `ema_13`. This is the exact band `app.portfolio.exits.evaluate_exit_flags` already tests against internally for the 'price reaches the upper Autoenvelope band with Impulse turning Red' existing-position exit rule (docs/Analyse.md §7), now exposed for any ticker rather than only a held portfolio position. Null for the first ~100 trading days of a ticker's history (the rolling deviation-average window isn't yet full) -- a much longer warm-up than any other field here, so this is null far more often than `ema_13`/`ema_26`/`macd_histogram`/`bull_power`/`bear_power`, which only need up to 26 bars.
             */
            channel_upper?: number | null;
            /** Ema 13 */
            ema_13: number;
            /** Ema 26 */
            ema_26: number;
            /** Macd Histogram */
            macd_histogram: number;
            /**
             * Rsi
             * @description Relative Strength Index (docs/Analyse.md §4, Elder ch. 27) -- `100 - 100 / (1 + RS)`, RS = average net up-close / average net down-close over a 9-day window (simple/arithmetic rolling average, not Wilder's smoothed variant -- see `app.indicators.rsi.rsi`). Closing-price-only, unlike `stochastic_k` (which also reads high/low) -- Elder's own selling point for it: less noisy, signals tend to emerge earlier. Computation + exposure only; not currently wired into `screens`/`confidence_breakdown` (see the backend-indicator-rsi task). Null for the first 9 trading days of a ticker's history (needs 9 daily closing changes) -- a much shorter warm-up than `channel_upper`/`channel_lower`.
             */
            rsi?: number | null;
        };
        /** OHLCVBar */
        OHLCVBar: {
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Volume */
            volume: number;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            equity: components["schemas"]["Equity"];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
        };
        /** PositionIn */
        PositionIn: {
            /**
             * Avg Cost Basis
             * @description Price paid per share for this lot. On merge with an existing position, this is blended into a quantity-weighted average, not overwritten. Must be a positive, finite number (Infinity/NaN are rejected).
             */
            avg_cost_basis: number;
            /**
             * Entry Date
             * Format: date
             * @description Date this lot was purchased. On merge with an existing position, the earlier of the two entry dates is kept.
             */
            entry_date: string;
            /**
             * Quantity
             * @description Number of shares being added. Must be a positive, finite number (Infinity/NaN are rejected) — this endpoint only adds to a position; use DELETE /api/portfolio/positions/{id} to remove one.
             */
            quantity: number;
            /**
             * Ticker
             * @description Stock ticker symbol, normalized to uppercase (leading/trailing whitespace is stripped). Adding a ticker that's already held merges into the existing position (quantity-weighted average cost basis) rather than creating a duplicate row — see the api-portfolio-add-position task's decisions.
             */
            ticker: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Avg Cost Basis */
            avg_cost_basis: number;
            /**
             * Confidence
             * @description Same 0-100 weighted composite score as AnalysisResponse.confidence. Null under the same condition as `signal`.
             */
            confidence?: number | null;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70. Null under the same condition as `signal`.
             */
            confidence_band?: ("Low" | "Medium" | "High") | null;
            /**
             * Current Price
             * @description Null only if the latest price fetch for this ticker failed.
             */
            current_price?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Id */
            id: string;
            /** Quantity */
            quantity: number;
            /**
             * Signal
             * @description BUY/SELL/HOLD from the exact same Triple Screen signal engine GET /api/stocks/{ticker}/analysis and GET /api/watchlist use (docs/Analyse.md §5) -- not a separately-implemented buy check. Null if this position's signal couldn't be computed right now -- either its current_price fetch already failed (see current_price's own description), that fetch succeeded but the separate weekly-history fetch the signal engine additionally needs (for Screen 1/Tide) failed, or the latest daily bar has a valid close (so current_price is still available) but NaN open/high/low and so doesn't survive the signal engine's stricter filtering -- mirroring WatchlistItemOut's null-on-failure pattern rather than failing the whole request or dropping the position. See the api-portfolio-position-signal task's `decisions`.
             */
            signal?: ("BUY" | "SELL" | "HOLD") | null;
            /** Ticker */
            ticker: string;
            /**
             * Unrealized Pnl Pct
             * @description (current_price - avg_cost_basis) / avg_cost_basis, as a percentage. Null under the same condition as current_price.
             */
            unrealized_pnl_pct?: number | null;
        };
        /** RiskPosition */
        RiskPosition: {
            /**
             * Exit Flags
             * @description Risk-driven exit reasons, e.g. 'stop_hit', 'tide_flipped_bearish' (docs/Analyse.md §7). Independent of this stock's fresh entry signal — can be non-empty even when /analysis says HOLD.
             */
            exit_flags: string[];
            /** Id */
            id: string;
            /**
             * Position Risk Pct
             * @description Fraction of current account equity lost if this position hits its protective_stop (the 2% rule).
             */
            position_risk_pct: number;
            /**
             * Protective Stop
             * @description Recent swing low minus a volatility buffer (SafeZone concept, docs/Analyse.md §7).
             */
            protective_stop: number;
            /** Ticker */
            ticker: string;
            /** Two Percent Rule Breached */
            two_percent_rule_breached: boolean;
        };
        /** RiskResponse */
        RiskResponse: {
            /** Positions */
            positions: components["schemas"]["RiskPosition"][];
            /**
             * Realized Losses This Month Pct
             * @description This calendar month's realized losses from closed_trades (only losing trades count; a profitable month contributes 0, never a negative offset to open risk), as a percentage of current account equity -- the component total_open_risk_pct above was missing before this field existed, per the backend-trade-history-table task. See DELETE /api/portfolio/positions/{id} for how a closed_trades row is recorded.
             */
            realized_losses_this_month_pct: number;
            /** Six Percent Rule Breached */
            six_percent_rule_breached: boolean;
            /**
             * Total Open Risk Pct
             * @description The 6% rule total: sum of position_risk_pct across all open positions plus realized_losses_this_month_pct below (docs/Analyse.md §7's own two-part formula -- 'the sum of your losses for the current month AND the risks in open trades', per docs/ideas.md's ch. 51 cross-check). Kept under this existing field name rather than renamed, since it's the one this response has always compared against the 6% threshold — see the backend-trade-history-table task's `decisions` entry.
             */
            total_open_risk_pct: number;
        };
        /** Screens */
        Screens: {
            /**
             * Impulse
             * @description Impulse System gate (docs/Analyse.md §3). RED blocks fresh BUY signals, GREEN blocks fresh SELL signals.
             * @enum {string}
             */
            impulse: "GREEN" | "RED" | "BLUE";
            tide: components["schemas"]["TideScreen"];
            trigger: components["schemas"]["TriggerScreen"];
            wave: components["schemas"]["WaveScreen"];
        };
        /** SupportResistanceZone */
        SupportResistanceZone: {
            /**
             * Break Date
             * @description Date of the confirmed break. Null if never broken.
             */
            break_date?: string | null;
            /**
             * Broken
             * @description Whether a daily close has confirmed a permanent break beyond this zone (a true breakout, distinct from false_breakout below) since its last touch -- role has already flipped to the opposite of its original side in that case.
             */
            broken: boolean;
            /**
             * Dollar Volume
             * @description Elder's own dollar-strength formula: days-in-zone x average daily volume x average price, over the zone's own touch span. Informational only -- not folded into strength_score, since the book gives no absolute dollar-value thresholds to classify it against.
             */
            dollar_volume: number;
            /** @description The most recent false-breakout episode detected for this zone (docs/ideas.md, Elder ch. 18: price closes beyond the zone, then closes back inside it -- a specific, high-value reversal signal). Null if none detected. Can be non-null even when broken is also true, if an earlier false breakout was followed by a later, separate breakout that did hold. */
            false_breakout?: components["schemas"]["FalseBreakoutOut"] | null;
            /**
             * First Touch Date
             * Format: date
             * @description Date of the earliest swing point clustered into this zone.
             */
            first_touch_date: string;
            /**
             * Height Category
             * @description Elder ch. 18's height-based strength factor: minor ~1%, intermediate ~3%, major >=7% of current price.
             * @enum {string}
             */
            height_category: "minor" | "intermediate" | "major";
            /**
             * Height Pct
             * @description Zone height (upper - lower) as a percentage of the ticker's current (latest) close.
             */
            height_pct: number;
            /**
             * Last Touch Date
             * Format: date
             * @description Date of the most recent swing point clustered into this zone.
             */
            last_touch_date: string;
            /**
             * Length Category
             * @description Elder ch. 18's length-based strength factor: minor ~2 weeks, intermediate ~2 months, major ~2 years.
             * @enum {string}
             */
            length_category: "minor" | "intermediate" | "major";
            /**
             * Length Days
             * @description Calendar days between first_touch_date and last_touch_date.
             */
            length_days: number;
            /**
             * Lower
             * @description Lower edge, mirrored.
             */
            lower: number;
            /**
             * Role
             * @description Current role. A zone keeps existing with an inverted role after a confirmed (non-false) breakout rather than being discarded -- resistance price has since broken above and held becomes support, and vice versa.
             * @enum {string}
             */
            role: "support" | "resistance";
            /**
             * Strength Score
             * @description 0-100 composite of length_category and height_category only (see dollar_volume's own description for why). A rule-based composite, like `confidence` (docs/Analyse.md §6) -- not a statistical probability.
             */
            strength_score: number;
            /**
             * Touch Count
             * @description Number of swing points clustered into this zone (always >= 2).
             */
            touch_count: number;
            /**
             * Upper
             * @description Upper edge of the horizontal congestion zone -- built from the clustered swing points' own closing prices, not the single most extreme high/low wick.
             */
            upper: number;
        };
        /** TideScreen */
        TideScreen: {
            /**
             * Trend
             * @description Screen 1 output (docs/Analyse.md §2). NEUTRAL when weekly MACD-Histogram slope and the 13/26-week EMA relationship disagree.
             * @enum {string}
             */
            trend: "BULLISH" | "BEARISH" | "NEUTRAL";
            /**
             * Weekly Macd Histogram Slope
             * @enum {string}
             */
            weekly_macd_histogram_slope: "rising" | "falling" | "flat";
        };
        /** TriggerScreen */
        TriggerScreen: {
            /**
             * Fired
             * @description Whether Screen 3 confirmed price has resumed the tide's direction.
             */
            fired: boolean;
            /**
             * Reference
             * @description Which trigger rule fired, e.g. 'close_above_prior_high'.
             */
            reference: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistItemIn */
        WatchlistItemIn: {
            /**
             * Ticker
             * @description Stock ticker symbol to watch, normalized to uppercase (leading/trailing whitespace is stripped). Adding a ticker already on the watchlist is a no-op that returns the existing entry unchanged (original added_at kept) rather than creating a duplicate row or rejecting with 409/422 -- see the api-watchlist task's `decisions`.
             */
            ticker: string;
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /**
             * Added At
             * Format: date-time
             * @description When this ticker was added to the watchlist (UTC).
             */
            added_at: string;
            /**
             * Confidence
             * @description Same 0-100 weighted composite score as AnalysisResponse.confidence. Null under the same condition as `signal`.
             */
            confidence?: number | null;
            /**
             * Confidence Band
             * @description Low <40, Medium 40-70, High >70. Null under the same condition as `signal`.
             */
            confidence_band?: ("Low" | "Medium" | "High") | null;
            /**
             * Signal
             * @description BUY/SELL/HOLD from the exact same Triple Screen signal engine GET /api/stocks/{ticker}/analysis uses (docs/Analyse.md §5) -- not a separately-implemented buy check. Null only if the signal couldn't be computed for this ticker right now (unknown/delisted ticker, insufficient history, or the data provider being unavailable), mirroring PositionOut's current_price null-on-failure pattern -- see the api-watchlist task's `decisions`.
             */
            signal?: ("BUY" | "SELL" | "HOLD") | null;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /**
             * Items
             * @description Every watched ticker, ordered by when it was added (oldest first).
             */
            items: components["schemas"]["WatchlistItemOut"][];
        };
        /** WaveScreen */
        WaveScreen: {
            /**
             * Force Index 2Ema
             * @description Force Index, 2-period EMA smoothing (entry-timing variant, not the 13-period trend-confirmation one).
             */
            force_index_2ema: number;
            /**
             * Showed Pullback In Lookback
             * @description Whether Screen 2 showed OVERSOLD_PULLBACK on any of the last 5 trading days (today inclusive), not just today -- docs/Analyse.md §5's 'Wave shows/showed oversold pullback' language, and the exact condition `_determine_signal` (backend/app/signals/engine.py) gates a fresh BUY on (see `_wave_lookback`'s own docstring). A BUY can therefore occur even when `state` above isn't OVERSOLD_PULLBACK today, if it was on an earlier day within the window -- this field is what lets a client (e.g. a signal explanation) distinguish that case from the condition never having been met at all. Null when `screens.tide.trend` is NEUTRAL, since Wave is evaluated against a tide direction that doesn't exist in that case -- neither this nor showed_rally_in_lookback is ever reachable, so `False` would misleadingly read as 'checked, and it didn't happen' rather than 'not applicable'.
             */
            showed_pullback_in_lookback: boolean | null;
            /**
             * Showed Rally In Lookback
             * @description Same as showed_pullback_in_lookback, mirrored for OVERBOUGHT_RALLY / the SELL side (what `_determine_signal` gates a fresh SELL on). Exactly one of these two fields is ever the 'reachable' one for a given non-Neutral tide (BULLISH -> only showed_pullback_in_lookback can be true; BEARISH -> only showed_rally_in_lookback can be true) -- the other is `False`, not null, since that's itself a real (if structurally guaranteed) fact about this tide, not a not-applicable case.
             */
            showed_rally_in_lookback: boolean | null;
            /**
             * State
             * @description Human-readable wave state, e.g. 'OVERSOLD_PULLBACK' — evaluated against the tide direction, not in isolation (docs/Analyse.md §2). Reflects only TODAY's bar -- see showed_pullback_in_lookback/showed_rally_in_lookback below for whether the qualifying state appeared on an earlier day within the signal's own lookback window.
             */
            state: string;
            /**
             * Stochastic K
             * @description Stochastic %K (5,3,3). Values below 30 are oversold, above 70 are overbought (docs/Analyse.md §4).
             */
            stochastic_k: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    get_closed_trades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosedTradesResponse"];
                };
            };
        };
    };
    add_position: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: ordinary request-body validation failure (FastAPI's standard HTTPValidationError — `detail` is a list of per-field errors), or merging with an existing position would produce a quantity/avg_cost_basis too large to represent (`detail` is a single string, ErrorDetail). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    delete_position: {
        parameters: {
            query?: {
                /** @description Why this position is being closed, from Elder's own taxonomy (docs/Analyse.md §7 / docs/ideas.md's ch. 51 cross-check). Defaults to 'unspecified' -- not one of Elder's own tags -- when the caller doesn't supply one, since this endpoint has no other way to know why the user is closing the position. */
                exit_reason?: components["schemas"]["ExitReason"];
            };
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_risk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
        };
    };
    get_stock_analysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Insufficient history to compute weekly indicators */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_stock_history: {
        parameters: {
            query?: {
                /** @description Lookback window: '<N>d' | '<N>w' | '<N>m' | '<N>y' (e.g. '1y', '6m', '90d'), or 'max' for full available history. Trimmed from the most recent bar actually returned, not from today's date. */
                range?: string;
                interval?: "daily" | "weekly";
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: `range` doesn't match the accepted pattern (FastAPI's standard HTTPValidationError — `detail` is a list of per-field errors), or the requested weekly interval has fewer than 26 weeks of history (`detail` is a single string, ErrorDetail) — same dual-shape pattern as `POST /api/portfolio/positions`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_stock_indicator_history: {
        parameters: {
            query?: {
                /** @description Same lookback-window grammar as GET /api/stocks/{ticker}/history's `range`: '<N>d' | '<N>w' | '<N>m' | '<N>y' (e.g. '1y', '6m', '90d'), or 'max' for full available history. Trimmed from the most recent bar actually returned, not from today's date. Daily bars only -- unlike /history, this endpoint has no `interval` param, since every indicator/Screen it computes (docs/Analyse.md §4) is itself daily-cadence; see this task's `decisions` entry. */
                range?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorHistoryResponse"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Either of two distinct shapes, both under HTTP 422: `range` doesn't match the accepted pattern (FastAPI's standard HTTPValidationError -- `detail` is a list of per-field errors), or the ticker has fewer than 26 weeks of weekly history to compute Screen 1's Tide (`detail` is a single string, ErrorDetail) -- same dual-shape pattern as `GET /api/stocks/{ticker}/history`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"] | components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Market data provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    add_watchlist_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticker not on the watchlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
