"""Regression tests for the Alembic setup (app/db/migrations/) -- both paths described in
docs/tasks/db-migrations.json's checklist and docs/architecture/Backend.md §7:

1. A fresh database: `alembic upgrade head` must build the full schema from nothing.
2. A database already seeded by the app/main.py `Base.metadata.create_all` stopgap: a blind
   `alembic upgrade head` must fail (CREATE TABLE against tables that already exist), and
   `alembic stamp head` is the correct way to mark it as already migrated.

These invoke the real `alembic` CLI as a subprocess (matching how a developer/operator would
actually run it) against a throwaway SQLite file, with `FINTRADE_DATABASE_URL` overriding the
target database for that invocation -- see app/db/migrations/env.py, which always reads the DB
URL from app.config.get_settings() rather than alembic.ini's static sqlalchemy.url. No network
call is made; sqlite3 is stdlib only.
"""

import os
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

from app.db.models import Base

BACKEND_DIR = Path(__file__).resolve().parents[2]


def _run_alembic(*args: str, database_url: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=BACKEND_DIR,
        env={**os.environ, "FINTRADE_DATABASE_URL": database_url},
        capture_output=True,
        text=True,
        timeout=60,
    )


def _tables(db_path: Path) -> set[str]:
    con = sqlite3.connect(db_path)
    try:
        rows = con.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
    finally:
        con.close()
    return {row[0] for row in rows}


def _table_columns(db_path: Path, table: str) -> set[str]:
    con = sqlite3.connect(db_path)
    try:
        rows = con.execute(f"PRAGMA table_info({table})").fetchall()
    finally:
        con.close()
    return {row[1] for row in rows}


class TestUpgradeHeadAgainstAFreshDatabase:
    def test_creates_the_full_expected_schema(self, tmp_path: Path) -> None:
        db_path = tmp_path / "fresh.db"
        result = _run_alembic("upgrade", "head", database_url=f"sqlite:///{db_path}")

        assert result.returncode == 0, result.stderr
        assert db_path.exists()

        tables = _tables(db_path)
        assert {
            "positions",
            "account",
            "ohlcv_cache",
            "watchlist_items",
            "closed_trades",
            "alembic_version",
        } <= tables

        # Column names match app/db/models.py's ORM definitions, confirming the
        # autogenerated migration wasn't hand-edited out of sync with the models.
        assert _table_columns(db_path, "positions") == {
            "id",
            "ticker",
            "quantity",
            "avg_cost_basis",
            "entry_date",
            "entry_notes",
            "strategy",
        }
        assert _table_columns(db_path, "account") == {"id", "cash"}
        assert _table_columns(db_path, "ohlcv_cache") == {
            "ticker",
            "date",
            "interval",
            "open",
            "high",
            "low",
            "close",
            "volume",
            "fetched_at",
        }
        assert _table_columns(db_path, "watchlist_items") == {"ticker", "added_at"}
        assert _table_columns(db_path, "closed_trades") == {
            "id",
            "ticker",
            "quantity",
            "entry_price",
            "entry_date",
            "exit_price",
            "exit_date",
            "realized_pnl",
            "exit_reason",
            "entry_notes",
            "strategy",
        }

    def test_records_the_head_revision_in_alembic_version(self, tmp_path: Path) -> None:
        db_path = tmp_path / "fresh.db"
        _run_alembic("upgrade", "head", database_url=f"sqlite:///{db_path}")

        con = sqlite3.connect(db_path)
        try:
            rows = con.execute("SELECT version_num FROM alembic_version").fetchall()
        finally:
            con.close()
        assert len(rows) == 1


class TestAgainstACreateAllSeededDatabase:
    """Reproduces app/main.py's lifespan create_all stopgap (docs/architecture/Backend.md
    §7): a database whose tables already exist, created without Alembic's involvement."""

    @pytest.fixture
    def seeded_db(self, tmp_path: Path) -> Path:
        db_path = tmp_path / "seeded.db"
        from sqlalchemy import create_engine

        engine = create_engine(f"sqlite:///{db_path}")
        try:
            Base.metadata.create_all(bind=engine)
        finally:
            engine.dispose()
        return db_path

    def test_blind_upgrade_head_fails(self, seeded_db: Path) -> None:
        result = _run_alembic("upgrade", "head", database_url=f"sqlite:///{seeded_db}")

        assert result.returncode != 0
        assert "already exists" in result.stderr

    def test_stamp_head_marks_it_up_to_date_without_touching_the_schema(self, seeded_db: Path) -> None:
        tables_before = _tables(seeded_db)

        result = _run_alembic("stamp", "head", database_url=f"sqlite:///{seeded_db}")
        assert result.returncode == 0, result.stderr

        assert _tables(seeded_db) == tables_before | {"alembic_version"}

        con = sqlite3.connect(seeded_db)
        try:
            rows = con.execute("SELECT version_num FROM alembic_version").fetchall()
        finally:
            con.close()
        assert len(rows) == 1

    def test_upgrade_head_is_a_no_op_after_stamping(self, seeded_db: Path) -> None:
        _run_alembic("stamp", "head", database_url=f"sqlite:///{seeded_db}")

        result = _run_alembic("upgrade", "head", database_url=f"sqlite:///{seeded_db}")

        assert result.returncode == 0, result.stderr
