"""add closed_trades table

Revision ID: 2e81d22e2f96
Revises: e1503fd151de
Create Date: 2026-09-19 10:25:53.484292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e81d22e2f96'
down_revision: Union[str, Sequence[str], None] = 'e1503fd151de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_trades_exit_date'), 'closed_trades', ['exit_date'], unique=False)
    op.create_index(op.f('ix_closed_trades_ticker'), 'closed_trades', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_closed_trades_ticker'), table_name='closed_trades')
    op.drop_index(op.f('ix_closed_trades_exit_date'), table_name='closed_trades')
    op.drop_table('closed_trades')
    # ### end Alembic commands ###
