"""add trailing_stop_high_water_mark to positions

Revision ID: 322370cba3c8
Revises: 6342c679ea48
Create Date: 2026-09-21 23:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322370cba3c8'
down_revision: Union[str, Sequence[str], None] = '6342c679ea48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('trailing_stop_high_water_mark', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'trailing_stop_high_water_mark')
    # ### end Alembic commands ###
