"""add strategy to positions and closed_trades

Revision ID: 54a0a4105106
Revises: f9d808fbe05c
Create Date: 2026-09-21 02:47:34.243952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a0a4105106'
down_revision: Union[str, Sequence[str], None] = 'f9d808fbe05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_trades', sa.Column('strategy', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('strategy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'strategy')
    op.drop_column('closed_trades', 'strategy')
    # ### end Alembic commands ###
