"""add indicator history cache table

Revision ID: 6342c679ea48
Revises: 800bdd065b2b
Create Date: 2026-09-21 10:11:58.531550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6342c679ea48'
down_revision: Union[str, Sequence[str], None] = '800bdd065b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_history_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('response_json', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'range')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_history_cache')
    # ### end Alembic commands ###
