"""initial schema

Revision ID: 6fae12abf862
Revises: 
Create Date: 2026-09-16 08:19:17.078745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fae12abf862'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohlcv_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date', 'interval')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost_basis', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_ticker'), 'positions', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_ticker'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('ohlcv_cache')
    op.drop_table('account')
    # ### end Alembic commands ###
