"""add daily_homework_entries table

Revision ID: 7d2a1f8a6ca8
Revises: a9adc10fa37c
Create Date: 2026-09-21 01:27:48.741389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2a1f8a6ca8'
down_revision: Union[str, Sequence[str], None] = 'a9adc10fa37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_homework_entries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('physical_state_score', sa.Integer(), nullable=False),
    sa.Column('yesterday_trading_score', sa.Integer(), nullable=False),
    sa.Column('trade_planning_score', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('schedule_score', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_homework_entries')
    # ### end Alembic commands ###
