"""add follow-up review fields to closed trades

Revision ID: 800bdd065b2b
Revises: 54a0a4105106
Create Date: 2026-09-21 04:06:14.886814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800bdd065b2b'
down_revision: Union[str, Sequence[str], None] = '54a0a4105106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_trades', sa.Column('follow_up_notes', sa.String(), nullable=True))
    op.add_column('closed_trades', sa.Column('follow_up_reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('closed_trades', 'follow_up_reviewed_at')
    op.drop_column('closed_trades', 'follow_up_notes')
    # ### end Alembic commands ###
