"""add extended_data_cache table

Revision ID: 8e8f24da49e7
Revises: 2e81d22e2f96
Create Date: 2026-09-20 06:47:14.590060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8f24da49e7'
down_revision: Union[str, Sequence[str], None] = '2e81d22e2f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extended_data_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.Column('shares_short', sa.Integer(), nullable=True),
    sa.Column('short_ratio', sa.Float(), nullable=True),
    sa.Column('short_percent_of_float', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Integer(), nullable=True),
    sa.Column('insider_transactions_json', sa.String(), nullable=False),
    sa.Column('unavailable_reason', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extended_data_cache')
    # ### end Alembic commands ###
