"""add entry_notes to positions and closed_trades

Revision ID: a9adc10fa37c
Revises: 8e8f24da49e7
Create Date: 2026-09-20 23:52:32.631402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9adc10fa37c'
down_revision: Union[str, Sequence[str], None] = '8e8f24da49e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_trades', sa.Column('entry_notes', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('entry_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'entry_notes')
    op.drop_column('closed_trades', 'entry_notes')
    # ### end Alembic commands ###
