"""add trading_mode_settings table

Revision ID: ac306d064b63
Revises: 322370cba3c8
Create Date: 2026-09-24 16:41:28.714211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac306d064b63'
down_revision: Union[str, Sequence[str], None] = '322370cba3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_mode_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('day_trader_long_term', sa.String(), nullable=True),
    sa.Column('day_trader_intermediate', sa.String(), nullable=True),
    sa.Column('day_trader_short_term', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_mode_settings')
    # ### end Alembic commands ###
