"""add source to ohlcv_cache

Revision ID: b9428ca17553
Revises: ac306d064b63
Create Date: 2026-10-01 20:56:46.371521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9428ca17553'
down_revision: Union[str, Sequence[str], None] = 'ac306d064b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlcv_cache', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohlcv_cache', 'source')
    # ### end Alembic commands ###
