"""add ibkr conid cache table

Revision ID: c8216d30fc10
Revises: f9c52e69b04a
Create Date: 2026-10-03 22:26:15.567111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8216d30fc10'
down_revision: Union[str, Sequence[str], None] = 'f9c52e69b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibkr_conid_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibkr_conid_cache')
    # ### end Alembic commands ###
