"""add cftc_cot_cache table

Revision ID: f9c52e69b04a
Revises: b9428ca17553
Create Date: 2026-10-03 13:10:02.202727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c52e69b04a'
down_revision: Union[str, Sequence[str], None] = 'b9428ca17553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cftc_cot_cache',
    sa.Column('market_key', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('commercial_long', sa.Integer(), nullable=False),
    sa.Column('commercial_short', sa.Integer(), nullable=False),
    sa.Column('large_speculator_long', sa.Integer(), nullable=False),
    sa.Column('large_speculator_short', sa.Integer(), nullable=False),
    sa.Column('small_speculator_long', sa.Integer(), nullable=False),
    sa.Column('small_speculator_short', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('market_key', 'report_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cftc_cot_cache')
    # ### end Alembic commands ###
