"""add ibkr_breadth_snapshots table

Revision ID: f9d808fbe05c
Revises: 7d2a1f8a6ca8
Create Date: 2026-09-21 02:16:49.354177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d808fbe05c'
down_revision: Union[str, Sequence[str], None] = '7d2a1f8a6ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibkr_breadth_snapshots',
    sa.Column('series_key', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('series_key', 'snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibkr_breadth_snapshots')
    # ### end Alembic commands ###
